## **1) Temel Bilgiler:**

### **1.1 Numpy Nedir?**
   - Numpy'nin temel amacı
   - Neden numpy kullanmalıyız?
   - Numpy'nin Özellikleri
   - Python listeleri ile numpy dizileri arasındaki farklar

### **1.2 Numpy Dizileri (Arrays)**
   - Numpy Arrayleri Nedir?
   - Array Oluşturma
      - np.zeros(), np.ones(), np.empty() vs.
      - np.arange(), np.linspace()
      - Random sayı üretimi: np.random.rand(), np.random.randn(), vs.
   - Array Özellikleri: Şekil, Boyut
   - Dizilerin Veri Tipleri
   - Dizilerin İndekslenmesi ve Dilimlenmesi

--- 


## **2) Temel İşlemler:**

### **2.1 Dizi İşlemleri:**
   - Dizi elemanlarına erişim
   - Aritmetik İşlemler
   - Diziler Arası İşlemler
   - Rastgele sayılar üretme

### **2.2 Array Şekil Değiştirme**
   - Dizinin Şeklini Değiştirme
   - Dizileri Birleştirme ve Ayırma

### **2.3 Matematiksel İşlemler**
   - Temel matematiksel işlemler (toplama, çıkarma, çarpma, bölme)
   - Matematiksel fonksiyonlar (sin, cos, exp, vs.)
   - İşlem hızı ve verimlilik

### **2.4 Veri Tipi Dönüşümleri**
   - Veri Tipi Dönüşümleri
   - Veri Tipi Sınırlamaları ve İşlem Önerileri

### **2.5 Fancy Indexing:**
   - Maskelerle Indexleme
   - Integer Indexleme

### **2.6 Array Operasyonları:**
   - Broadcasting (Yayılma)
      - Numpy'nin Yayılma (broadcasting) Kavramı
      - Yayılma Kuralları
      - Örneklerle Yayılma Kullanımı
   - Dizi Birleştirme (Concatenation)
   - Dizi Bölme (Splitting)
   - Dizi Yineleme (Repeating)
   - İç Çarpım (dot product)
   - İşlem fonksiyonları (np.sum(), np.prod(), np.mean() vs.)

---

## **3. Lineer Cebir İşlemleri**
   - Matris çarpımı
   - Determinant ve ters matris hesaplama
   - Lineer cebir işlemleri uygulama örnekleri

## **4) Veri Manipülasyonu:**

### **4.1 Dizi Şekillendirme ve Yeniden Düzenleme:**
   - Dizi Şeklini Değiştirme
   - Dizi Birleştirme ve Yığınlama

### **4.2 Dizi Operasyonları:**
   - Transpozisyon
   - Yeniden Şekillendirme ve Yeniden Düzenleme
   - Dizilerin Birleştirilmesi ve Ayırılması

---

## **5) Daha İleri Konular:**

### **5.1 Universal Functions (ufuncs):**
   - Neden Ufuncs Kullanılır?
   - Ufuncs Nasıl Kullanılır?

### **5.2. Numpy İleri Operasyonlar:**
   - Dizilerin indekslenmesi ve dilimlenmesi (ilave detaylar)
   - Dizilerin sıralanması ve terslenmesi
   - Dizi Filtreleme ve Koşullu Mantık
   - Dizi Sıralama ve İstatistik

### **5.3 Paralel hesaplama ve çok iş parçacıklı (multithreading) programlama**

---

## **6) Performans Optimizasyonu**
   - Numpy'nin performans avantajları
   - Vektörize edilmiş kodun önemi
   - Performans ipuçları ve hızlı numpy kodlama teknikleri

## **7) Dosya İşlemleri**
   - Dizi verilerini dosyaya yazma ve okuma
   - CSV dosyalarıyla çalışma
   - Numpy dizilerini kaydetme ve yükleme

## **8) Numpy ile Veri Analizi ve Görselleştirme**
   - Veri analizi için numpy kullanımı
   - Numpy ile veri görselleştirme

## **9) Uygulamalar ve Örnekler**
   - Numpy'nin gerçek dünya uygulamaları
   - Örnek projeler ve problemler

## **1.1 Numpy Nedir?**

Numpy, Python programlama dili için temel bir kütüphanedir ve bilimsel hesaplama ve veri işleme için kullanılır. Numpy'nin temel amacı, Python'da veri işlemesi ve hesaplamaları yapmak için hızlı ve etkili bir şekilde çalışabilecek yüksek performanslı çok boyutlu diziler ve matematiksel işlevler sunmaktır.

### **Neden Numpy Kullanmalıyız?**

Numpy'nin kullanılmasının bazı avantajları şunlardır:
- **Hızlı ve Verimli İşlemler:** Numpy, C ve Fortran dilinde yazılmış alt seviye optimizasyonlar kullanır, bu da Python'da yavaş olan bazı işlemleri hızlandırır.
- **Diziler Üzerinde Hızlı İşlemler:** Numpy dizileri, Python listelerine göre daha hızlı ve verimli işlemler yapmak için optimize edilmiştir.
- **Geniş Fonksiyonellik:** Numpy, matematiksel işlevler, rastgele sayı üretimi, lineer cebir işlemleri gibi birçok faydalı fonksiyon ve işlev içerir.
- **Veri Analizi ve Bilimsel Hesaplama:** Numpy, veri analizi, bilimsel hesaplama, simülasyonlar ve modeller gibi çeşitli alanlarda yaygın olarak kullanılır.

### **Numpy'nin Özellikleri**

Numpy'nin bazı temel özellikleri şunlardır:
- **Çok Boyutlu Diziler (Arrays):** Numpy, çok boyutlu dizileri destekler. Bu, tek boyutlu vektörlerden çok boyutlu matrislere kadar geniş bir veri yelpazesini kapsar.
- **Matematiksel İşlevler:** Numpy, temel matematiksel işlevler (sin, cos, exp vb.) ve işlemler (toplama, çıkarma, çarpma, bölme vb.) için fonksiyonlar içerir.
- **Yüksek Performanslı Hesaplama:** Numpy, vektörize edilmiş işlemler ve alt seviye optimizasyonlar kullanarak yüksek performanslı hesaplamalar sağlar.
- **Geniş Kullanım Alanı:** Numpy, veri analizi, bilimsel hesaplama, makine öğrenmesi, görüntü işleme gibi birçok alanda kullanılır.

### **Python Listeleri ile Numpy Dizileri Arasındaki Farklar**

Numpy dizileri ile Python listeleri arasındaki temel farklar şunlardır:
1. **Performans:** Numpy dizileri, Python listelerine göre daha hızlı ve verimli işlemler yapar. Bu, özellikle büyük veri kümeleri üzerinde çalışırken belirgin hale gelir.
2. **Veri Tipi ve Boyut Kontrolü:** Numpy dizileri, elemanları aynı veri tipinde tutar ve sabit bir boyuta sahiptir. Bu, veri kümeleri üzerinde homojen işlemler yapmayı kolaylaştırır.
3. **Matematiksel İşlemler:** Numpy dizileri, matematiksel işlemler için optimize edilmiş vektörize edilmiş işlemleri destekler. Bu, Python listelerinden daha hızlı ve daha kolay matematiksel işlemler yapmayı sağlar.
4. **Bellek Yönetimi:** Numpy dizileri, veriyi daha etkin bir şekilde bellekte depolar ve işler. Bu, bellek kullanımını optimize eder ve verimliliği artırır.


| Numpy Dizileri                             | Python Listeleri                           |
|--------------------------------------------|--------------------------------------------|
| Numpy dizileri aynı türde verileri içerir. | Python listeleri farklı türde verileri içerebilir. |
| Numpy dizileri boyutları sabittir.        | Python listeleri dinamik boyutlara sahiptir. |
| Numpy dizilerinde vektörleştirilmiş işlemler yapılabilir, bu da performansı artırır. | Python listelerinde döngüler kullanılarak işlemler yapılır, bu performansı düşürebilir. |

---

## **1.2 Numpy Dizileri (Arrays)**

Numpy, Python'da bilimsel hesaplamalar yapmak için kullanılan temel bir kütüphanedir. En önemli özelliklerinden biri, çok boyutlu (çok boyutlu) dizilerle çalışabilme yeteneğidir. Bu çok boyutlu dizilere "Numpy array" denir.

---

### **1.2.1 Numpy Array Nedir?**

Numpy array, homojen veri tiplerinden oluşan bir grid yapısıdır. Bir numpy array, aynı türde veriler içerir ve boyutları sabittir. Numpy array'leri, Python listelerine benzerdir ancak daha etkin ve hızlıdır.

#### **Numpy Array Özellikleri**

1. **Homojen Veri Tipi:**
   - Numpy array'leri, aynı türde verileri içerir. Bu, veri işleme ve matematiksel operasyonlar için çok önemlidir çünkü her eleman aynı veri türüne sahiptir.

2. **Sabit Boyut:**
   - Numpy array'lerinin boyutları oluşturulduktan sonra değiştirilemez. Bu, bellek kullanımını optimize eder ve hızlı işlemler sağlar.

3. **Hızlı ve Verimli:**
   - Numpy, C altında derlenmiş bir kütüphanedir, bu da işlemlerin hızlı ve verimli bir şekilde yapılmasını sağlar. Büyük veri kümeleriyle çalışırken performans avantajı sağlar.

4. **Çok Boyutlu Yetenek:**
   - Numpy array'leri, tek boyutlu, iki boyutlu ve daha fazla boyutta olabilir. Bu, matematiksel ve bilimsel hesaplamalarda çok yönlü kullanım sağlar.

---

#### **Python Listeleri ile Numpy Arrayleri Arasındaki Farklar**

Numpy array'leri ve Python listeleri arasındaki ana farklar şunlardır:

- **Performans:**
   - Numpy array'leri, vektörleştirilmiş operasyonlar ve optimize edilmiş bellek kullanımı sayesinde Python listelerinden daha hızlıdır.
   
- **Veri Tipi Kontrolü:**
   - Numpy array'leri homojen veri tipleri içerirken, Python listeleri heterojen veri tipleri içerebilir.
   
- **Boyut Değiştirme:**
   - Numpy array'lerinin boyutları oluşturulduktan sonra değiştirilemezken, Python listelerinin boyutu dinamik olarak değiştirilebilir.

- **Matematiksel İşlemler:**
   - Numpy array'leri, matematiksel işlemleri vektörleştirme yeteneği ile desteklerken, Python listeleri bunu doğrudan desteklemez.

Bu farklar, Numpy'nin Python listelerine tercih edilmesinin temel nedenlerindendir. Numpy array'leri, bilimsel hesaplamalar, veri analizi ve makine öğrenimi gibi uygulamalarda yaygın olarak kullanılmaktadır.

---
### **1.2.2 Array Oluşturma**

Numpy kütüphanesi, çeşitli yöntemlerle array oluşturmayı sağlar. Bu yöntemler, farklı ihtiyaçlara göre farklı türde arrayler oluşturmanıza olanak tanır.

#### **1.2.2.1 `np.zeros()`, `np.ones()`, `np.empty()`**

Bu fonksiyonlar, belirli bir şekilde sıfırlar, birler veya boş değerler içeren arrayler oluşturur. Temel kullanımı aşağıdaki gibidir:

- `np.zeros(shape)`: Belirtilen boyutta sıfırlardan oluşan bir array oluşturur.
- `np.ones(shape)`: Belirtilen boyutta birlerden oluşan bir array oluşturur.
- `np.empty(shape)`: Belirtilen boyutta boş değerler içeren bir array oluşturur. Bu array'in değerleri, bellekteki mevcut duruma bağlı olarak değişkenlik gösterebilir.
---

In [16]:
import numpy as np

zeros_array = np.zeros((2, 3))  # 2x3 boyutunda sıfırlardan oluşan array
print(zeros_array, "\n")
# Çıktı:
# [[0. 0. 0.]
#  [0. 0. 0.]]

ones_array = np.ones((3, 2))  # 3x2 boyutunda birlerden oluşan array
print(ones_array,"\n")
# Çıktı:
# [[1. 1.]
#  [1. 1.]
#  [1. 1.]]

empty_array = np.empty((2, 2))  # 2x2 boyutunda boş değerler içeren array
print(empty_array)
# Çıktı:
# [[4.67296746e-307 1.69121096e-306]
#  [8.34441742e-308 1.24611470e-306]]

[[0. 0. 0.]
 [0. 0. 0.]] 

[[1. 1.]
 [1. 1.]
 [1. 1.]] 

[[0.18693    0.47300576]
 [0.89733236 0.34079692]]


---

#### **1.2.2.2 `np.arange()`, `np.linspace()`**

Bu fonksiyonlar, belirli bir aralıktaki sayılarla dolu arrayler oluşturur.

- `np.arange(start, stop, step)`: Belirli bir aralıktaki sayıları belirtilen adımlarla içeren bir array oluşturur.
- `np.linspace(start, stop, num)`: Belirli bir aralıktaki belirli sayıda eşit aralıklı sayıları içeren bir array oluşturur.

---

In [17]:
import numpy as np

range_array = np.arange(0, 10, 2)  # 0'dan 10'a kadar 2'şer artan sayılar
print(range_array, "\n")
# Çıktı: [0 2 4 6 8]

linspace_array = np.linspace(0, 10, 5)  # 0'dan 10'a kadar 5 eşit aralıklı sayılar
print(linspace_array)
# Çıktı: [ 0.   2.5  5.   7.5 10. ]

[0 2 4 6 8] 

[ 0.   2.5  5.   7.5 10. ]


#### ** 1.2.2.3 Random Sayı Üretimi: `np.random.rand()`, `np.random.randn()`**

Bu fonksiyonlar, belirli bir boyutta rastgele sayılar içeren arrayler oluşturur.

- `np.random.rand(d0, d1, ..., dn)`: 0 ile 1 arasında uniform dağılımlı rastgele sayılar içeren bir array oluşturur.
- `np.random.randn(d0, d1, ..., dn)`: Ortalaması 0 ve standart sapması 1 olan normal dağılımlı rastgele sayılar içeren bir array oluşturur.

In [18]:
import numpy as np

random_array_uniform = np.random.rand(2, 2)  # 2x2 boyutunda uniform dağılımlı rastgele sayılar
print(random_array_uniform,"\n")


random_array_normal = np.random.randn(2, 2)  # 2x2 boyutunda normal dağılımlı rastgele sayılar
print(random_array_normal)

[[0.87837508 0.44783032]
 [0.11237035 0.16647509]] 

[[0.01635255 0.59053157]
 [1.2391599  0.39864723]]


### **1.2.3 Array Özellikleri: Şekil, Boyut**

Numpy array'lerinin şekli ve boyutu, array'in yapısını ve içerdiği veri miktarını tanımlar. Bu özellikler, array üzerinde işlem yaparken ve verileri manipüle ederken oldukça önemlidir.

#### **Array Şekli (Shape)**

Bir array'in şekli, her boyuttaki eleman sayısını içeren bir tuple'dır. Örneğin, bir 2x3 boyutundaki array'in şekli `(2, 3)` şeklinde ifade edilir.

#### **Array Boyutu (Dimension)**

Bir array'in boyutu, içerdiği boyut sayısını ifade eder. Örneğin, 2x3 boyutundaki bir array 2 boyutlu (2D) olarak kabul edilir.

In [19]:
import numpy as np

# 2x3 boyutunda bir array oluşturalım
my_array = np.array([[1, 2, 3],
                    [4, 5, 6]])

print("Array Şekli (Shape):", my_array.shape)  # Çıktı: (2, 3)
print("Array Boyutu (Dimension):", my_array.ndim)  # Çıktı: 2

Array Şekli (Shape): (2, 3)
Array Boyutu (Dimension): 2


#### **Reshaping (Yeniden Şekillendirme)**

Numpy, `reshape()` fonksiyonu aracılığıyla mevcut bir array'in şeklini değiştirmenize olanak tanır. Bu işlem, array'in boyutunu değiştirmez, sadece şeklini yeniden düzenler.

In [20]:
import numpy as np

# 2x3 boyutunda bir array oluşturalım
my_array = np.array([[1, 2, 3],
                    [4, 5, 6]])

# Array'in şeklini (2, 3)ten (3, 2)'ye çevirelim
reshaped_array = my_array.reshape((3, 2))

print("Yeniden Şekillendirilmiş Array:")
print(reshaped_array)

Yeniden Şekillendirilmiş Array:
[[1 2]
 [3 4]
 [5 6]]


* Yukarıdaki örnekte, `reshape()` fonksiyonu kullanılarak `my_array` adlı array'in şekli (2, 3)'ten (3, 2)'ye çevrildi.

#### **Array'in Boyutunu Değiştirme**

Numpy, `reshape()` fonksiyonu dışında array'in boyutunu değiştiren `resize()` fonksiyonunu da sağlar. Bu fonksiyon, mevcut array'i değiştirir ve istenen boyuta uyacak şekilde genişletir veya kısaltır.

In [21]:
import numpy as np

# 2x3 boyutunda bir array oluşturalım
my_array = np.array([[1, 2, 3],
                    [4, 5, 6]])

# Array'in boyutunu (3, 4)'e değiştirelim
resized_array = np.resize(my_array, (3, 4))

print("Yeniden Boyutlandırılmış Array:")
print(resized_array)

Yeniden Boyutlandırılmış Array:
[[1 2 3 4]
 [5 6 1 2]
 [3 4 5 6]]


* Yukarıdaki örnekte, `resize()` fonksiyonu kullanılarak `my_array` adlı array'in boyutu (3, 4)'e değiştirildi.

### **1.2.4 Dizilerin Veri Tipleri**

Numpy dizileri, homojen veri tipleriyle (aynı tipte verileri içerir) çalışır. Bu, her bir öğenin aynı veri tipine sahip olması gerektiği anlamına gelir. Numpy, farklı türlerde veri tiplerini destekler ve her bir veri tipi farklı boyut ve işlemlere izin verir.

#### **Numpy Veri Tipleri:**

1. **int**: Tam sayılar.
2. **float**: Ondalık sayılar.
3. **complex**: Karmaşık sayılar.
4. **bool**: Mantıksal (Boolean) değerler.
5. **string**: Karakter dizileri.
6. **object**: Python nesneleri için genel veri tipi.
7. **datetime**: Tarih ve saat veri tipleri.

#### **Veri Tipi Belirtme**

Numpy, bir dizi oluştururken veya bir diziye dönüştürürken veri tipini belirlemenize izin verir. Bu, bellek kullanımını optimize etmenize ve beklenmeyen sonuçlardan kaçınmanıza olanak tanır.

In [22]:
import numpy as np

# Diziyi oluştururken veri tipini belirleme
my_array = np.array([1, 2, 3], dtype=float)
print("Float tipinde dizi:", my_array)

# Dönüştürme işlemi sırasında veri tipini belirleme
converted_array = np.array([1, 2, 3], dtype=float)
print("Dönüştürülen dizi:", converted_array)

Float tipinde dizi: [1. 2. 3.]
Dönüştürülen dizi: [1. 2. 3.]


### **1.2.5 Dizilerin İndekslenmesi ve Dilimlenmesi**

Numpy dizileri, Python listelerine benzer şekilde indekslenir ve dilimlenir. Bu işlemler, belirli bir elemana erişmek veya belirli bir alt küme oluşturmak için kullanılır. Numpy, çok boyutlu dizilerle çalışırken bu işlemleri daha da güçlendirir.

#### **1.2.5.1 İndeksleme**

Numpy dizileri, 0'dan başlayarak indekslenir. Bir dizinin belirli bir elemanına erişmek için indeks numarasını kullanırız.

In [23]:
import numpy as np

# 1D dizinin oluşturulması
arr = np.array([1, 2, 3, 4, 5])

# İndeksleme
print(arr[0])  # Çıktı: 1
print(arr[2])  # Çıktı: 3

1
3


#### **1.2.5.2 Dilimleme (Slicing)**

Dilimleme, bir dizinin belirli bir alt kümesini seçmek için kullanılır. Numpy dizilerinde dilimleme, Python listelerinden çok benzer şekilde çalışır. `[start:stop:step]` formülü kullanılır. Herhangi bir parametre belirtilmezse, varsayılan değerler kullanılır (başlangıç: 0, durdurma: son, adım: 1).

In [24]:
import numpy as np

# 1D dizinin oluşturulması
arr = np.array([1, 2, 3, 4, 5])

# Dilimleme
print(arr[1:4])  # Çıktı: [2 3 4]
print(arr[:3])   # Çıktı: [1 2 3]
print(arr[::2])  # Çıktı: [1 3 5]

[2 3 4]
[1 2 3]
[1 3 5]


#### **1.2.5.3 Çok Boyutlu Dizilerde İndeksleme ve Dilimleme**

Çok boyutlu dizilerde, her boyuta ait bir indeks veya dilimleme kullanabiliriz. Her boyut için indeksleme ve dilimleme işlemleri virgülle ayrılır.

In [25]:
import numpy as np

# 2D dizinin oluşturulması
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# İndeksleme ve Dilimleme
print(arr[0, 0])     # Çıktı: 1 (1. satırın 1. sütunu)
print(arr[1, 2])     # Çıktı: 6 (2. satırın 3. sütunu)
print(arr[:2, 1:])   # Çıktı: [[2 3]
                            #   [5 6]]

1
6
[[2 3]
 [5 6]]
